### ISSUE TITLE
Can I retrieve some json data from js into html template ?

### ISSUE THREAD

**Issue by daniel-mnt** [Smile-SA/grunt-build-html#11]
Hello there. This is a question, not an issue. I'm sorry in advance if this is offtopic.

This is my code:

```
dev:{
                options: {
                    templates: './src/html/partials/**/*.html',
                    data: 'plugins.json'
                },
                expand: true,
                cwd: 'src/html/',
                src: ['*.html'],
                dest: 'build/',
                ext: '.html'
            }
```

How can I retrieve data from plugins.json in my template file ?

**Comment by astik** [comment]
Once you add the data configuration in gruntfile like you did above in the example, all data contained into this json is exposed to your template.

For example, if you have this JSON content :

```
{
	"foobar": "woot",
	"bla": {"blo":"bli"}
}
```

You can access this content into your template :

```
<%=bla.blo%>
<br />
<%=foobar%>
```

You should get :
```
bli
<br />
woot
```
